# Generated by Django 4.2.4 on 2023-10-01 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=100)),
                ('selling_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.TextField()),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('T-W-C', 'Two-wheeled cart'), ('F-W-C', 'Four-wheeled cart'), ('M-C-C', 'Multifunctional cargo cart'), ('F-C-C', 'Foldable cargo cart')], max_length=6)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_customer', models.CharField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='VN')),
                ('address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id_cart', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
