# Generated by Django 4.2.4 on 2023-10-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_order_id',
        ),
    ]
