# Generated by Django 4.2.4 on 2023-10-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_payment_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
