# Generated by Django 4.2.4 on 2023-10-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_payment_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_product',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
