# Generated by Django 4.2.4 on 2023-11-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
