# Generated by Django 4.2.4 on 2023-11-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='payment_trans_id',
        ),
    ]
