# Generated by Django 4.2.4 on 2023-11-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_payment_id_payment_payment_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Peding', 'Đang chờ'), ('On the way', 'Đang giao'), ('Delivered', 'Hoàn tất'), ('Cancel', 'Huỷ')], default='Peding', max_length=50),
        ),
    ]
