# Generated by Django 4.2.4 on 2023-11-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Chấp nhận', 'Chấp nhận'), ('Đang chờ', 'Đang chờ'), ('Đang giao', 'Đang giao'), ('Hoàn tất', 'Hoàn tất'), ('Huỷ', 'Huỷ')], default='Đang chờ', max_length=50),
        ),
    ]
